spring:
  application:
    name: app-common

springdoc:
  api-docs:
    groups:
      enabled: true
    swagger-ui:
      enabled: true     

app.mybatis-plus:
  auto-fill:
    enabled: true
  sql-debug:
    enabled: true